# Generated by Django 3.2.8 on 2023-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0004_auto_20230718_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_10',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_11',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_12',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_7',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_8',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_9',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_4',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_4',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_4',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_4',
            field=models.CharField(default='', max_length=250),
        ),
    ]
