# Generated by Django 3.2.8 on 2023-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0006_add_on_programme_college_affiliation_bangalore_add_on_programme_college_affiliation_kerla_affiliated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.CharField(max_length=250)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
