# Generated by Django 3.2.8 on 2023-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0007_visitor_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_registration',
            old_name='admission_month_and_year',
            new_name='admission_date',
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='practical_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_mark_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='contact_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='course_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='exam_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='id_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='add_on_programme',
            name='student_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='admission_registration',
            name='address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='affliation_from_date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='affliation_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='affliation_to_date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='center_address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='cost_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='date_of_appointment_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='date_of_appointment_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='date_of_appointment_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='date_of_appointment_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='designation_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='designation_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='designation_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='designation_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='education_institution_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='form_receive_date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='information_serial_number_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='information_serial_number_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='information_serial_number_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='information_serial_number_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='name_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='name_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='name_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='name_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_of_room_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='number_terminal_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='other_facility_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='pincode',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='postal_address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='qualification_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='qualification_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='qualification_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='qualification_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='registration_fee',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='residential_address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='seating_capacity_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='serial_number_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='software_facility_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='status_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='status_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='status_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='status_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='teaching_experience_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='teaching_experience_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='teaching_experience_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='teaching_experience_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_affliation_fee',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='total_area_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='type_of_computer_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_1',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application_for_affliation',
            name='year_of_purchase_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_10',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_7',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_8',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='file_number_9',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_10',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_7',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_8',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='serial_number_9',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_10',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_7',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_8',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_daily_work_statement',
            name='work_name_9',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_leave_status',
            name='distance_walking_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_leave_status',
            name='distance_walking_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_leave_status',
            name='purpose_2',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_leave_status',
            name='purpose_3',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_leave_status',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='advance',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='age_of_child_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='age_of_child_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='child_name_2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='child_name_3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='employee_grade',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='employee_liablity',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='employee_promotion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='loan',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='scale_of_pay',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='showcase_notice',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_employee_record',
            name='suspension',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_office_file_sanction',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exam_registration',
            name='online_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='external_marks_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='final_mark_verified_officer_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_10',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_11',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_12',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_7',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_8',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='grade_9',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='internal_marks_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_check_clerk_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_enter_clerk_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='mark_obtained_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='result_enter_register_book_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='second_verified_officer_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_10',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_11',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_12',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_5',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_6',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_7',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_8',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='subject_9',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_mark_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='total_mark_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='viva_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pay_online_fees',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pay_online_fees',
            name='remark',
            field=models.TextField(max_length=250),
        ),
    ]
