# Generated by Django 3.2.8 on 2023-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0008_auto_20230724_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_registration',
            name='registration_number',
            field=models.IntegerField(default=1000),
        ),
    ]
