# Generated by Django 4.2.5 on 2023-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0013_vtc_course_admission_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='external_marks_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_13',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='grade_14',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='internal_marks_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mark_obtained_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_13',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='subject_14',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='total_14',
            field=models.IntegerField(default=0),
        ),
    ]
