# Generated by Django 4.2.5 on 2023-11-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0014_mark_list_registration_external_marks_13_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_list_registration',
            name='subject_13',
        ),
        migrations.RemoveField(
            model_name='mark_list_registration',
            name='subject_14',
        ),
    ]
