# Generated by Django 4.2.5 on 2023-11-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0015_remove_mark_list_registration_subject_13_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_list_registration',
            name='practical_mark',
        ),
        migrations.RemoveField(
            model_name='mark_list_registration',
            name='viva_mark',
        ),
    ]
