# Generated by Django 5.0 on 2024-01-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0017_exam_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_list_registration',
            name='address',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='admission_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='admission_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='any_fees_concession',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='college_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationalyouth.college_name'),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationalyouth.course_name'),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='district',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='exam_attendance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='exam_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationalyouth.exam_fees_type'),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='id_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='name_of_student',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='online_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='principal_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationalyouth.status'),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='principal_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='principal_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
