# Generated by Django 5.0 on 2024-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0019_mark_list_registration_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250)),
                ('news_image', models.ImageField(upload_to='image/download/uploads/news_image/')),
                ('news_description', models.TextField()),
                ('news_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
