# Generated by Django 5.0 on 2024-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0021_alter_news_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free_Skill_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(upload_to='image/download/uploads/skill_image/')),
                ('skill_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
