# Generated by Django 5.0 on 2024-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0022_free_skill_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_list_registration',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/download/uploads/certificate_image/'),
        ),
        migrations.AddField(
            model_name='mark_list_registration',
            name='marklist_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/download/uploads/marklist_image/'),
        ),
    ]
